BYEBUG_SERVER_PORT: '1048'
DB_USER:
SENDGRID_USER:
SENDGRID_PASS:
TWITTER_CONSUMER_KEY:
TWITTER_CONSUMER_SECRET:
TWITTER_ACCESS_TOKEN:
TWITTER_ACCESS_SECRET:
VERZION: '1.0.0'
FADE_TIME: '30'
S3_BUCKET_NAME:
S3_ACCESS_KEY_ID:
S3_SECRET_ACCESS_KEY:

development:
  MAILER_HOST: localhost:3000
  DB_PASS:
  DEFAULT_HOST: vell.dev
test:
  DB_PASS: n0rails4u
  DEFAULT_HOST: localhost:3000
production:
  SECRET_KEY_BASE:
  SECRET_TOKEN:
  DEFAULT_HOST: https://www.lovell.direct
  DB_PASS:
