# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 456749ff4499fe9c71a167bb7fee3824ec1c55055b9db76a414a6db406e97fc4d037b3210af7bd9875eb86d488ae994eb8c5bba77176451f987f98d525b7feaa

test:
  secret_key_base: 10c923c5f6a654618689cdee15e7a52674ef3056db697af78d05ab856cee3854d934f42b458681563c88d190814ffd2566ec5e93ef324fdb9610dc71c2d52904

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_token: <%= ENV['SECRET_TOKEN']%>
